from typing import List, Optional
from datetime import datetime, timezone
from fastapi import APIRouter, Depends, Query, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc

from backend.app.core.database import get_db
from backend.app.models.forecast import Forecast
from backend.app.models.reading import StationReading
from backend.app.models.weather import WeatherSnapshot
from backend.app.models.station import Station
from backend.app.analytics.forecaster import CityAirQualityForecaster

router = APIRouter()


@router.get("/")
async def list_forecasts(
    city: Optional[str] = Query(None, description="Filter by city name"),
    horizon: Optional[int] = Query(None, description="Horizon in hours (24, 48, 72)"),
    db: AsyncSession = Depends(get_db)
):
    """
    Returns multi-horizon (+24h, +48h, +72h) PM2.5 and AQI forecasts generated by local city XGBoost models.
    Includes prediction intervals (10th-90th percentiles).
    If data is thin, explicitly flags 'is_insufficient_data: true'.
    """
    stmt = select(Forecast)
    if city:
        stmt = stmt.where(Forecast.city == city)
    if horizon:
        stmt = stmt.where(Forecast.horizon_hours == horizon)
    stmt = stmt.order_by(desc(Forecast.created_at)).limit(50)

    forecasts = (await db.execute(stmt)).scalars().all()

    return [
        {
            "id": f.id,
            "city": f.city,
            "horizon_hours": f.horizon_hours,
            "target_timestamp": f.target_timestamp,
            "predicted_pm25": f.predicted_pm25,
            "predicted_aqi": f.predicted_aqi,
            "aqi_category": f.aqi_category,
            "lower_bound_pm25": f.lower_bound_pm25,
            "upper_bound_pm25": f.upper_bound_pm25,
            "model_version": f.model_version,
            "is_insufficient_data": f.is_insufficient_data,
            "created_at": f.created_at,
        }
        for f in forecasts
    ]


@router.post("/generate", status_code=status.HTTP_201_CREATED)
async def generate_city_forecast(
    city: str = Query("Delhi-NCR", description="Target city for multi-horizon forecast"),
    db: AsyncSession = Depends(get_db)
):
    """
    Runs CityAirQualityForecaster (+24h, +48h, +72h) using actual station telemetry
    and Open-Meteo weather snapshots.
    Strictly sets is_insufficient_data=True if continuous training observations < 48 hours.
    """
    # 1. Fetch station readings for the city
    r_stmt = (
        select(StationReading)
        .join(Station, Station.id == StationReading.station_id)
        .where(Station.city == city)
        .where(StationReading.parameter == "pm25")
        .order_by(StationReading.timestamp)
    )
    readings = (await db.execute(r_stmt)).scalars().all()

    # 2. Fetch weather snapshots for the city
    w_stmt = (
        select(WeatherSnapshot)
        .where(WeatherSnapshot.city == city)
        .order_by(WeatherSnapshot.timestamp)
    )
    weather_snapshots = (await db.execute(w_stmt)).scalars().all()

    # 3. Execute Forecaster
    forecaster = CityAirQualityForecaster(city=city)
    new_forecasts = forecaster.generate_forecasts(
        readings=readings,
        weather_snapshots=weather_snapshots
    )

    # 4. Save to DB
    for fc in new_forecasts:
        db.add(fc)

    await db.commit()

    return {
        "message": f"Generated {len(new_forecasts)} forecasts for {city}.",
        "city": city,
        "is_insufficient_data": any(f.is_insufficient_data for f in new_forecasts),
        "forecasts": [
            {
                "id": f.id,
                "horizon_hours": f.horizon_hours,
                "target_timestamp": f.target_timestamp,
                "predicted_pm25": f.predicted_pm25,
                "predicted_aqi": f.predicted_aqi,
                "aqi_category": f.aqi_category,
                "lower_bound_pm25": f.lower_bound_pm25,
                "upper_bound_pm25": f.upper_bound_pm25,
                "is_insufficient_data": f.is_insufficient_data
            }
            for f in new_forecasts
        ]
    }
